# Define your own admin routes here
# Define your own admin routes here
sylius_admin_product_badge:
    resource: |
        alias: yac_dev_sylius_product_badge_plugin.product_badge
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: index
        grid: sylius_admin_product_badge
        form:
            type: YacDev\SyliusProductBadgePlugin\Form\Type\Admin\ProductBadgeType
    type: sylius.resource
