yac_dev_sylius_product_badge:
    css_classes:
        - "bg-primary"
        - "bg-secondary"
        - "bg-success"
        - "bg-danger"
        - "bg-warning"
        - "bg-info"
        - "bg-light"
        - "bg-dark"
